name: ApplicationPattern
services:
  app:
    type: Application
    namespace: test
    settings:
      replicas: 1
      containers:
        - name: svc-demo
          image: utkarsh23/meshy:v5
          ports:
            - name: http
              containerPort: 8080
