# Generated by Django 3.0.5 on 2020-05-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_english', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=7.0)),
                ('ongoing', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genre', models.ManyToManyField(to='core.AnimeCategory')),
            ],
            options={
                'verbose_name': 'Anime',
            },
        ),
    ]
