# Generated by Django 3.0.6 on 2020-05-11 07:21

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='insights',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.InsightDetails'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cyberpunk', 'Cyberpunk'), ('Game', 'Game'), ('Ecchi', 'Ecchi'), ('Demons', 'Demons'), ('Harem', 'Harem'), ('Josei', 'Josei'), ('Martial Arts', 'Martial Arts'), ('Kids', 'Kids'), ('Historical', 'Historical'), ('Hentai', 'Hentai'), ('Isekai', 'Isekai'), ('Military', 'Military'), ('Mecha', 'Mecha'), ('Music', 'Music'), ('Parody', 'Parody'), ('Police', 'Police'), ('Post-Apocalyptic', 'Post-Apocalyptic'), ('Reverse Harem', 'Reverse Harem'), ('School', 'School'), ('Seinen', 'Seinen'), ('Shoujo', 'Shoujo'), ('Shoujo-ai', 'Shoujo-ai'), ('Shounen', 'Shounen'), ('Shounen-ai', 'Shounen-ai'), ('Space', 'Space'), ('Sports', 'Sports'), ('Super Power', 'Super Power'), ('Tragedy', 'Tragedy'), ('Vampire', 'Vampire'), ('Yuri', 'Yuri'), ('Yaoi', 'Yaoi')], max_length=249),
        ),
    ]
