# Generated by Django 3.0.5 on 2020-05-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.CharField(choices=[('DA', 'Dual Audio'), ('S', 'Subbed'), ('D', 'Dubbed')], default='Subbed', max_length=30),
        ),
    ]
