# Generated by Django 3.0.5 on 2020-05-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='language',
            field=models.CharField(choices=[('Dual Audio', 'Dual Audio'), ('Subbed', 'Subbed'), ('Dubbed', 'Dubbed')], default='Subbed', max_length=30),
        ),
    ]
