# Generated by Django 3.0.6 on 2020-05-11 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200511_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='insights',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.InsightDetails'),
        ),
    ]
