# Generated by Django 3.0.6 on 2020-05-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200511_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightdetails',
            name='director',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
