# Generated by Django 3.0.5 on 2020-05-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_year_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_video', models.BooleanField()),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
