# Generated by Django 3.0.5 on 2020-05-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mediaattachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='media',
            field=models.ManyToManyField(to='core.MediaAttachments'),
        ),
    ]
