# Generated by Django 3.0.6 on 2020-05-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200511_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
