# Generated by Django 3.0.5 on 2020-05-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200508_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media',
            field=models.ManyToManyField(blank=True, to='core.MediaAttachments'),
        ),
    ]
