# Generated by Django 3.0.5 on 2020-05-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200508_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaattachments',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
