# Generated by Django 3.0.5 on 2020-05-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mediaattachments_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='characters',
            field=models.ManyToManyField(blank=True, to='core.Characters'),
        ),
        migrations.AddField(
            model_name='mediaattachments',
            name='characters',
            field=models.ManyToManyField(blank=True, to='core.Characters'),
        ),
    ]
