# Generated by Django 3.0.5 on 2020-05-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200508_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characters',
            options={'verbose_name_plural': 'Characters'},
        ),
        migrations.AddField(
            model_name='characters',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
    ]
