# Generated by Django 3.0.6 on 2020-05-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200511_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='editors_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='votes',
            field=models.IntegerField(default=1000),
        ),
    ]
