# Generated by Django 3.0.6 on 2020-05-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200512_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieitem',
            name='sub_genres',
        ),
    ]
