# Generated by Django 3.0.6 on 2020-05-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_movieitem_sub_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('runtime', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Videos, AMV, Trailers',
            },
        ),
    ]
