# Generated by Django 3.0.6 on 2020-05-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_videoitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitems',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
