# Generated by Django 3.0.6 on 2020-05-13 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_videoitems_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoitems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
