# Generated by Django 3.0.6 on 2020-05-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200513_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitems',
            name='runtime',
            field=models.FloatField(),
        ),
    ]
